clear all; close all

basedir = '/data/MITgcm_ASF-csi/newexp/analysis/';
addpath /data/MITgcm_ASF-csi/utils/matlab; 
addpath /data/MITgcm_ASF-csi/newexp/analysis;
addpath /data/MITgcm_ASF-csi/experiments/products;
addpath /data/MITgcm_ASF-csi/newexp/analysis/colormaps;

expdir = '/data/MITgcm_ASF-csi/experiments/';
outdir = '/data/MITgcm_ASF-csi/experiments/products';

fontsize = 15;
imgname = 'scalingMatrix';

       
load([outdir '/MomScalingMatrix.mat']);

%%
figure(1)
y = [Windstress(2,1) SIinternal(2,1) Topogform(2,1) Dissipation(2,1) OCN_AdvCor(2,1) SI_cor(2,1) RESIDUAL(2,1);...
     Windstress(2,2) SIinternal(2,2) Topogform(2,2) Dissipation(2,2) OCN_AdvCor(2,2) SI_cor(2,2) RESIDUAL(2,2);...
     Windstress(2,3) SIinternal(2,3) Topogform(2,3) Dissipation(2,3) OCN_AdvCor(2,3) SI_cor(2,3) RESIDUAL(2,3);...
     Windstress(1,1) SIinternal(1,1) Topogform(1,1) Dissipation(1,1) OCN_AdvCor(1,1) SI_cor(1,1) RESIDUAL(1,1);...
     Windstress(1,2) SIinternal(1,2) Topogform(1,2) Dissipation(1,2) OCN_AdvCor(1,2) SI_cor(1,2) RESIDUAL(1,2);...
     Windstress(1,3) SIinternal(1,3) Topogform(1,3) Dissipation(1,3) OCN_AdvCor(1,3) SI_cor(1,3) RESIDUAL(1,3);...
     Windstress(4,1) SIinternal(4,1) Topogform(4,1) Dissipation(4,1) OCN_AdvCor(4,1) SI_cor(4,1) RESIDUAL(4,1);...
     Windstress(4,2) SIinternal(4,2) Topogform(4,2) Dissipation(4,2) OCN_AdvCor(4,2) SI_cor(4,2) RESIDUAL(4,2);...
     Windstress(4,3) SIinternal(4,3) Topogform(4,3) Dissipation(4,3) OCN_AdvCor(4,3) SI_cor(4,3) RESIDUAL(4,3);...
     ];
BAR = bar(y,'stacked');
axis ij

set(gca,'fontsize',fontsize);
ylabel('Zonal force balance ($N/m^2$)', 'FontSize', fontsize,'interpreter','latex');
xlabel('Tidal current amplitude', 'FontSize', fontsize,'interpreter','latex');
legend('Wind stress',...
    'Sea ice internal stress',...
    'Topog. form stress',...
    'Dissipation',...
    'Ocean Adv.',...  
    'Sea ice Cori.',...
    'Residual term', 'FontSize', fontsize-2,'interpreter','latex');
set(BAR(7),'FaceColor',[225 225 225]/255);
title('','FontSize',fontsize+3,'interpreter','latex');
set(gcf,'position',[128 368 1166 548]);
set(gca,'xtick',[])

saveas(gcf,[outdir '/' imgname '/tide.png']);
saveas(gcf,[outdir '/' imgname '/tide.fig']);

%%

figure(2)

 y =[Windstress(5,1) SIinternal(5,1) Topogform(5,1) Dissipation(5,1) OCN_AdvCor(5,1) SI_cor(5,1) RESIDUAL(5,1);...
     Windstress(5,2) SIinternal(5,2) Topogform(5,2) Dissipation(5,2) OCN_AdvCor(5,2) SI_cor(5,2) RESIDUAL(5,2);...
     Windstress(5,3) SIinternal(5,3) Topogform(5,3) Dissipation(5,3) OCN_AdvCor(5,3) SI_cor(5,3) RESIDUAL(5,3);...
     ...
     Windstress(6,1) SIinternal(6,1) Topogform(6,1) Dissipation(6,1) OCN_AdvCor(6,1) SI_cor(6,1) RESIDUAL(6,1);...
     Windstress(6,2) SIinternal(6,2) Topogform(6,2) Dissipation(6,2) OCN_AdvCor(6,2) SI_cor(6,2) RESIDUAL(6,2);...
     Windstress(6,3) SIinternal(6,3) Topogform(6,3) Dissipation(6,3) OCN_AdvCor(6,3) SI_cor(6,3) RESIDUAL(6,3);...
     ...
     Windstress(1,1) SIinternal(1,1) Topogform(1,1) Dissipation(1,1) OCN_AdvCor(1,1) SI_cor(1,1) RESIDUAL(1,1);...
     Windstress(1,2) SIinternal(1,2) Topogform(1,2) Dissipation(1,2) OCN_AdvCor(1,2) SI_cor(1,2) RESIDUAL(1,2);...
     Windstress(1,3) SIinternal(1,3) Topogform(1,3) Dissipation(1,3) OCN_AdvCor(1,3) SI_cor(1,3) RESIDUAL(1,3);...
     ...
     Windstress(7,1) SIinternal(7,1) Topogform(7,1) Dissipation(7,1) OCN_AdvCor(7,1) SI_cor(7,1) RESIDUAL(7,1);...
     Windstress(7,2) SIinternal(7,2) Topogform(7,2) Dissipation(7,2) OCN_AdvCor(7,2) SI_cor(7,2) RESIDUAL(7,2);...
     Windstress(7,3) SIinternal(7,3) Topogform(7,3) Dissipation(7,3) OCN_AdvCor(7,3) SI_cor(7,3) RESIDUAL(7,3);...
     ...
     Windstress(9,1) SIinternal(9,1) Topogform(9,1) Dissipation(9,1) OCN_AdvCor(9,1) SI_cor(9,1) RESIDUAL(9,1);...
     Windstress(9,2) SIinternal(9,2) Topogform(9,2) Dissipation(9,2) OCN_AdvCor(9,2) SI_cor(9,2) RESIDUAL(9,2);...
     Windstress(9,3) SIinternal(9,3) Topogform(9,3) Dissipation(9,3) OCN_AdvCor(9,3) SI_cor(9,3) RESIDUAL(9,3);...
     ];
BAR = bar(y,'stacked');
axis ij
set(gca,'fontsize',fontsize);
ylabel('Zonal force balance ($N/m^2$)', 'FontSize', fontsize,'interpreter','latex');
xlabel('Buoyancy gradient', 'FontSize', fontsize,'interpreter','latex');
legend('Wind stress',...
    'Sea ice internal stress',...
    'Topog. form stress',...
    'Dissipation',...
    'Ocean Adv. + Cori.',...  
    'Sea ice Cori.',...
    'Residual term', 'FontSize', fontsize-2,'interpreter','latex');
set(BAR(7),'FaceColor',[225 225 225]/255);
title('','FontSize',fontsize+3,'interpreter','latex');
set(gcf,'position',[128 368 1166 548]);
set(gca,'xtick',[])

saveas(gcf,[outdir '/' imgname '/buoyancygradient.png']);
saveas(gcf,[outdir '/' imgname '/buoyancygradient.fig']);



%%
figure(3)
y = [Windstress(13,1) SIinternal(13,1) Topogform(13,1) Dissipation(13,1) OCN_AdvCor(13,1) SI_cor(13,1) RESIDUAL(13,1);...
     Windstress(13,2) SIinternal(13,2) Topogform(13,2) Dissipation(13,2) OCN_AdvCor(13,2) SI_cor(13,2) RESIDUAL(13,2);...
     Windstress(13,3) SIinternal(13,3) Topogform(13,3) Dissipation(13,3) OCN_AdvCor(13,3) SI_cor(13,3) RESIDUAL(13,3);...
     Windstress(1,1) SIinternal(1,1) Topogform(1,1) Dissipation(1,1) OCN_AdvCor(1,1) SI_cor(1,1) RESIDUAL(1,1);...
     Windstress(1,2) SIinternal(1,2) Topogform(1,2) Dissipation(1,2) OCN_AdvCor(1,2) SI_cor(1,2) RESIDUAL(1,2);...
     Windstress(1,3) SIinternal(1,3) Topogform(1,3) Dissipation(1,3) OCN_AdvCor(1,3) SI_cor(1,3) RESIDUAL(1,3);...
     Windstress(12,1) SIinternal(12,1) Topogform(12,1) Dissipation(12,1) OCN_AdvCor(12,1) SI_cor(12,1) RESIDUAL(12,1);...
     Windstress(12,2) SIinternal(12,2) Topogform(12,2) Dissipation(12,2) OCN_AdvCor(12,2) SI_cor(12,2) RESIDUAL(12,2);...
     Windstress(12,3) SIinternal(12,3) Topogform(12,3) Dissipation(12,3) OCN_AdvCor(12,3) SI_cor(12,3) RESIDUAL(12,3);...
     ];
BAR = bar(y,'stacked');
axis ij

set(gca,'fontsize',fontsize);
ylabel('Zonal force balance ($N/m^2$)', 'FontSize', fontsize,'interpreter','latex');
xlabel('Depth/Width of the bumps', 'FontSize', fontsize,'interpreter','latex');
legend('Wind stress',...
    'Sea ice internal stress',...
    'Topog. form stress',...
    'Dissipation',...
    'Ocean Adv. + Cori.',...  
    'Sea ice Cori.',...
    'Residual term', 'FontSize', fontsize-2,'interpreter','latex');
set(BAR(7),'FaceColor',[225 225 225]/255);
title('','FontSize',fontsize+3,'interpreter','latex');
set(gcf,'position',[128 368 1166 548]);
set(gca,'xtick',[])

saveas(gcf,[outdir '/' imgname '/bumps.png']);
saveas(gcf,[outdir '/' imgname '/bumps.fig']);


%% 
figure(4)
y = [Windstress(1,1) SIinternal(1,1) Topogform(1,1) Dissipation(1,1) OCN_AdvCor(1,1) SI_cor(1,1) RESIDUAL(1,1);...
     Windstress(1,2) SIinternal(1,2) Topogform(1,2) Dissipation(1,2) OCN_AdvCor(1,2) SI_cor(1,2) RESIDUAL(1,2);...
     Windstress(1,3) SIinternal(1,3) Topogform(1,3) Dissipation(1,3) OCN_AdvCor(1,3) SI_cor(1,3) RESIDUAL(1,3);...
     ...
     Windstress(10,1) SIinternal(10,1) Topogform(10,1) Dissipation(10,1) OCN_AdvCor(10,1) SI_cor(10,1) RESIDUAL(10,1);...
     Windstress(10,2) SIinternal(10,2) Topogform(10,2) Dissipation(10,2) OCN_AdvCor(10,2) SI_cor(10,2) RESIDUAL(10,2);...
     Windstress(10,3) SIinternal(10,3) Topogform(10,3) Dissipation(10,3) OCN_AdvCor(10,3) SI_cor(10,3) RESIDUAL(10,3);...
     ...
     Windstress(11,1) SIinternal(11,1) Topogform(11,1) Dissipation(11,1) OCN_AdvCor(11,1) SI_cor(11,1) RESIDUAL(11,1);...
     Windstress(11,2) SIinternal(11,2) Topogform(11,2) Dissipation(11,2) OCN_AdvCor(11,2) SI_cor(11,2) RESIDUAL(11,2);...
     Windstress(11,3) SIinternal(11,3) Topogform(11,3) Dissipation(11,3) OCN_AdvCor(11,3) SI_cor(11,3) RESIDUAL(11,3);...
     ];
BAR = bar(y,'stacked');
axis ij

set(gca,'fontsize',fontsize);
ylabel('Zonal force balance ($N/m^2$)', 'FontSize', fontsize,'interpreter','latex');
xlabel('Slope half-width', 'FontSize', fontsize,'interpreter','latex');
legend('Wind stress',...
    'Sea ice internal stress',...
    'Topog. form stress',...
    'Dissipation',...
    'Ocean Adv. + Cori.',...  
    'Sea ice Cori.',...
    'Residual term', 'FontSize', fontsize-2,'interpreter','latex');
set(BAR(7),'FaceColor',[225 225 225]/255);
title('','FontSize',fontsize+3,'interpreter','latex');
set(gcf,'position',[128 368 1166 548]);
set(gca,'xtick',[])

saveas(gcf,[outdir '/' imgname '/ws.png']);
saveas(gcf,[outdir '/' imgname '/ws.fig']);